### ISSUE TITLE
Would you be interested making this work MIT licence?

### ISSUE THREAD

**Issue by Ankcorn** [PalanQu/LoggingDrain#5]
Hi @PalanQu 

This is a great piece of work and I had a play with it, it works pretty well and it has the potential to massively improve template performance.

Have you considered adding a licence so others can use it?

Thanks
Thomas

**Comment by sundarv85** [comment]
Yes, a license addition would be great.

@Ankcorn  when you say it has a potential to massively improve template performance.. do you mean improvements can be done to the go version of this code base..

**Comment by PalanQu** [comment]
@Ankcorn Sorry for late response, I miss this information, I will add a licence in a minute.

**Comment by PalanQu** [comment]
Merged https://github.com/PalanQu/LoggingDrain/pull/7
